[startup.syncthing]
name = "syncthing"

[startup.syncthing.args]
loglevels_db = '*'
domain = "agent"
name = "syncthing"

[startup.jumpscript]
name = "js_daemon"

[startup.jumpscript.args]
max_restart = 10
domain = "agent"
name = "jumpscript"
